name: moodle_api
description: A dart client-side package for Moodle API implementing moodle web service functions.
version: 0.0.1
repository: https://github.com/amansikarwar/moodle_api

environment:
  sdk: '>=2.19.0-444.4.beta <3.0.0'

dependencies:
  fpdart: ^0.4.0
  http: ^0.13.5
  riverpod: ^2.1.3
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
